name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: app

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@main
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: app
        run: |
          west build -b nrf52dk_nrf52832

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            app/build/zephyr/zephyr.hex
            app/build/zephyr/zephyr.elf
            app/build/zephyr/zephyr.map
